version: '2'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra-seed-1:
    image: cassandra
    container_name: cassandra-seed-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-seed-1"
    ports:
      - "7000"
      - "9042"
      - "9160"
    restart: always

  cassandra-node:
    image: cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-seed-1"
    ports:
      - "7000"
      - "9042"
      - "9160"
    depends_on:
      - cassandra-seed-1
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_CREATE_TOPICS: "user_status_commands:3:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  userservice:
    image: userservice:1.0
    links:
      - "cassandra"
      - "kafka"
    depends_on:
      - cassandra
      - kafka
